spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:~/h2
    username: test
    password: test
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2